<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="6" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-01T12:35:13 IST" name="Suite" finished-at="2024-10-01T12:35:38 IST" duration-ms="25435">
    <groups>
    </groups>
    <test started-at="2024-10-01T12:35:13 IST" name="Test" finished-at="2024-10-01T12:35:26 IST" duration-ms="13441">
      <class name="testng.DemoLogin">
        <test-method signature="setup(java.lang.String)[pri:0, instance:testng.DemoLogin@294425a7]" started-at="2024-10-01T12:35:13 IST" name="setup" finished-at="2024-10-01T12:35:19 IST" duration-ms="6833" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="FullName()[pri:1, instance:testng.DemoLogin@294425a7]" started-at="2024-10-01T12:35:19 IST" name="FullName" finished-at="2024-10-01T12:35:20 IST" duration-ms="109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FullName -->
        <test-method signature="EnterEmail()[pri:2, instance:testng.DemoLogin@294425a7]" started-at="2024-10-01T12:35:20 IST" name="EnterEmail" finished-at="2024-10-01T12:35:20 IST" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterEmail -->
        <test-method signature="click_On_signup_button()[pri:3, instance:testng.DemoLogin@294425a7]" started-at="2024-10-01T12:35:20 IST" name="click_On_signup_button" finished-at="2024-10-01T12:35:21 IST" duration-ms="1159" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ENTER ACCOUNT INFORMATION] but found [ENTER... ACCOUNT INFORMATION]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ENTER ACCOUNT INFORMATION] but found [ENTER... ACCOUNT INFORMATION]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testng.DemoLogin.click_On_signup_button(DemoLogin.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- click_On_signup_button -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testng.DemoLogin@294425a7]" started-at="2024-10-01T12:35:21 IST" name="teardown" finished-at="2024-10-01T12:35:26 IST" duration-ms="5159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testng.DemoLogin -->
    </test> <!-- Test -->
    <test started-at="2024-10-01T12:35:26 IST" name="Test2" finished-at="2024-10-01T12:35:38 IST" duration-ms="11930">
      <class name="testng.DemoLogin">
        <test-method signature="setup(java.lang.String)[pri:0, instance:testng.DemoLogin@47eaca72]" started-at="2024-10-01T12:35:26 IST" name="setup" finished-at="2024-10-01T12:35:30 IST" duration-ms="3951" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="FullName()[pri:1, instance:testng.DemoLogin@47eaca72]" started-at="2024-10-01T12:35:30 IST" name="FullName" finished-at="2024-10-01T12:35:30 IST" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FullName -->
        <test-method signature="EnterEmail()[pri:2, instance:testng.DemoLogin@47eaca72]" started-at="2024-10-01T12:35:30 IST" name="EnterEmail" finished-at="2024-10-01T12:35:30 IST" duration-ms="102" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterEmail -->
        <test-method signature="click_On_signup_button()[pri:3, instance:testng.DemoLogin@47eaca72]" started-at="2024-10-01T12:35:30 IST" name="click_On_signup_button" finished-at="2024-10-01T12:35:33 IST" duration-ms="2554" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ENTER ACCOUNT INFORMATION] but found [ENTER... ACCOUNT INFORMATION]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ENTER ACCOUNT INFORMATION] but found [ENTER... ACCOUNT INFORMATION]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testng.DemoLogin.click_On_signup_button(DemoLogin.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- click_On_signup_button -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testng.DemoLogin@47eaca72]" started-at="2024-10-01T12:35:33 IST" name="teardown" finished-at="2024-10-01T12:35:38 IST" duration-ms="5194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testng.DemoLogin -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
